// Code generated by github.com/gobuffalo/packr. DO NOT EDIT

package goth

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
		packr.PackJSONBytes("../goth/templates", "actions/auth.go.tmpl", "\"H4sIAAAAAAAA/9RTzW7bPBA8i0+xH5EAJKCPcoueCuRgOEb/UDuwm0NPBS2vJMISqZCrOIWgdy8oKz9FAOfci0RqhjOzwrDV+UGXCDon42xgzDSt8wSCJbxoiLOEu8AZS3hpqOp2KndNVrpdVxS6dtn05n/jjfaHnSYMWemoOguOD5NzlvS917ZEUK1392aPPsD/w3D27BMz63vYu6PNdUBQMAycAfQ92v2oIRkrOpuDsYaEhJ4lJ1e1JecRrmDetkKqLYZgnB0/shNH3Qa8eXQRzyEvjN3jQwoXWGMDH69epe57UwDeTQSuO6pm/BF6ijqiw6BWeBQuqE9IaO8F7/uufYn/+rb8yWUK5yjb5WKz/BFZRUNq23pjqRD8MlwGnk4DfnaBUuBZTJO9jpHluq53Oj+85XW9/j7/snoz0WJ9s+RSpnFkrAP+O+NPmaf6vFxKNkxlmndULaYTIofpJqiFs4QPJAG9dz52rQvo07iNPZmKt3BNWyPhbUAfhUSuNhhaZwMKmULc3XUYSEjJktgk7+G/K7CmjoqJR+q8hVwto4n4MHs3GkiWDCzJMrh2EFyDVBlbwtFQBVQhnII0+vcOwWNpAqGPQJMFU9pxBcayZ/UN2j168X42S8Grr9v1SkQNGX/CnwAAAP//zZFqvjkEAAA=\"")
}
