name: Release
on:
  release:
    types:
      - published
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
